version: "3"

services:
  # Banco de Dados Postgres
  pg_nanowip:
    image: "postgres:13.3-alpine"
    container_name: pg_nanowip
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${POSTGRESS_DATABASE}"
      - "POSTGRES_USER=${POSTGRESS_USER}"
      - "POSTGRES_PASSWORD=${POSTGRESS_PASSWORD}"
    networks: 
      - nanowip
  
  # Cache Redis
  redis_nanowip:
    image: 'redis:alpine'
    container_name: redis_nanowip
    ports:
      - "6379:6379"
    networks: 
      - nanowip

  # Painel de adm para Redis
  redis_commander_nanowip:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander_nanowip
    hostname: redis-commander
    environment:
      - REDIS_HOSTS=local:redis_nanowip:6379
    ports:
      - "8081:8081"
    networks: 
      - nanowip
  
  # Metabase
  pg_metabase_nanowip:
    image: "postgres:13.3-alpine"
    container_name: pg_metabase_nanowip
    tty: true
    ports:
      - "5433:5432"
    volumes:
      - pg_metabase_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=metabase"
      - "POSTGRES_USER=${POSTGRESS_USER}"
      - "POSTGRES_PASSWORD=${POSTGRESS_PASSWORD}"
    networks: 
      - nanowip

  metabase_nanowip:
    image: metabase/metabase:latest
    container_name: metabase_nanowip
    hostname: metabase_nanowip
    ports:
      - "3001:3000"
    environment:
      - "MB_DB_HOST=pg_metabase_nanowip"
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=${POSTGRESS_USER}"
      - "MB_DB_PASS=${POSTGRESS_PASSWORD}"
    depends_on:
      - pg_metabase_nanowip
    networks:
      - nanowip
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pg_data:
    name: nanowip_pg_data
  pg_metabase_data:
    name: nanowip_pg_metabase_data

networks: 
  nanowip:
    name: 'nanowip'
    driver: 'bridge'
